package net.discraft.mod.gui.menu;

import com.google.common.collect.ImmutableList;
import com.mojang.realmsclient.gui.ChatFormatting;
import net.discraft.mod.Discraft;
import net.discraft.mod.DiscraftReferences;
import net.discraft.mod.gui.GuiUtils;
import net.discraft.mod.gui.ScissorState;
import net.discraft.mod.gui.api.*;
import net.discraft.mod.gui.container.GuiDiscraftContainerModules;
import net.discraft.mod.utils.NewsManager;
import net.minecraft.client.Minecraft;
import net.minecraft.client.audio.PositionedSoundRecord;
import net.minecraft.client.gui.*;
import net.minecraft.client.renderer.GlStateManager;
import net.minecraft.client.renderer.OpenGlHelper;
import net.minecraft.client.resources.I18n;
import net.minecraft.client.settings.GameSettings;
import net.minecraft.init.SoundEvents;
import net.minecraft.realms.RealmsBridge;
import net.minecraft.util.ResourceLocation;
import net.minecraft.util.StringUtils;
import net.minecraft.util.text.TextFormatting;
import net.minecraft.world.WorldServerDemo;
import net.minecraft.world.storage.ISaveFormat;
import net.minecraft.world.storage.WorldInfo;
import net.minecraftforge.fml.common.Loader;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.lwjgl.opengl.GLContext;

import java.io.IOException;
import java.net.URI;
import java.util.*;

@SideOnly(Side.CLIENT)
public class GuiDiscraftMainMenu extends GuiDiscraftScreen {

    public static final String MORE_INFO_TEXT = "Please click " + TextFormatting.UNDERLINE + "here" + TextFormatting.RESET + " for more information.";

    private static final Logger LOGGER = LogManager.getLogger();
    private static final Random RANDOM = new Random();

    private static final ResourceLocation SPLASH_TEXTS = new ResourceLocation("texts/splashes.txt");
    public static final ResourceLocation MENU_LOGO = new ResourceLocation(Discraft.MOD_ID + ":textures/gui/logo_main.png");

    private static float moduleFade = 0;

    private final GuiDiscraftScroller menuNewsContainer = new GuiDiscraftScroller(3, 0, 47, 247, 143, this);
    /**
     * The Object object utilized as a thread lock when performing non thread-safe operations
     */
    private final Object threadLock = new Object();
    public GuiDiscraftContainerModules containerModules;
    private GuiButton buttonResetDemo;
    /**
     * Width of openGLWarning2
     */
    private int openGLWarning2Width;
    /**
     * Width of openGLWarning1
     */
    private int openGLWarning1Width;
    /**
     * Left x coordinate of the OpenGL warning
     */
    private int openGLWarningX1;
    /**
     * Top y coordinate of the OpenGL warning
     */
    private int openGLWarningY1;
    /**
     * Right x coordinate of the OpenGL warning
     */
    private int openGLWarningX2;
    /**
     * Bottom y coordinate of the OpenGL warning
     */
    private int openGLWarningY2;
    /**
     * OpenGL graphics card warning.
     */
    private String openGLWarning1;
    /**
     * OpenGL graphics card warning.
     */
    private String openGLWarning2;
    /**
     * Link to the Mojang Support about minimum requirements
     */
    private String openGLWarningLink;
    /**
     * Minecraft Realms button.
     */
    private GuiButton realmsButton;
    /**
     * Has the check for a realms notification screen been performed?
     */
    private boolean hasCheckedForRealmsNotification;
    /**
     * A screen generated by realms for notifications; drawn in adition to the main menu (buttons and such from both are
     * drawn at the same time). May be null.
     */
    private GuiScreen realmsNotification;
    private GuiButton modButton;
    private net.minecraftforge.client.gui.NotificationModUpdateScreen modUpdateNotification;

    private static float introFade = 2;
    private static float introFadeFirst = 1f;
    private static boolean hasSeenIntro = false;
    private static boolean hasPlayedIntroSound = false;

    public GuiDiscraftMainMenu() {

        this.openGLWarning2 = MORE_INFO_TEXT;

        this.openGLWarning1 = "";

        if (!GLContext.getCapabilities().OpenGL20 && !OpenGlHelper.areShadersSupported()) {
            this.openGLWarning1 = I18n.format("title.oldgl1");
            this.openGLWarning2 = I18n.format("title.oldgl2");
            this.openGLWarningLink = "https://help.mojang.com/customer/portal/articles/325948?ref=game";
        }

    }

    /**
     * Is there currently a realms notification screen, and are realms notifications enabled?
     */
    private boolean areRealmsNotificationsEnabled() {
        return Minecraft.getMinecraft().gameSettings.getOptionOrdinalValue(GameSettings.Options.REALMS_NOTIFICATIONS) && this.realmsNotification != null;
    }

    /**
     * Called from the main game loop to update the screen.
     */
    @Override
    public void updateScreen() {
        super.updateScreen();

        if (this.areRealmsNotificationsEnabled()) {
            this.realmsNotification.updateScreen();
        }
    }

    /**
     * Returns true if this GUI should pause the game when it is displayed in single-player
     */
    public boolean doesGuiPauseGame() {
        return false;
    }

    /**
     * Fired when a key is typed (except F11 which toggles full screen). This is the equivalent of
     * KeyListener.keyTyped(KeyEvent e). Args : character (character on the key), keyCode (lwjgl Keyboard key code)
     */
    protected void keyTyped(char typedChar, int keyCode) {
    }

    /**
     * Adds the buttons (and other controls) to the screen in question. Called when the GUI is displayed and when the
     * window resizes, the buttonList is cleared beforehand.
     */
    @Override
    public void initGui() {
        super.initGui();

        int buttonWidth = 100;

        int x = width / 2 - 173;
        this.menuNewsContainer.posX = x + 104;
        this.menuNewsContainer.posY = 47;
        this.menuNewsContainer.height = 140;

        addContainer(this.menuNewsContainer);

        this.menuNewsContainer.setTextList(Collections.singletonList("&cLoading News & Updates..."));
        new Thread() {

            public void run() {
                try {
                    injectNews(NewsManager.getNewsAsStringList());
                } catch (IOException e) {
                    e.printStackTrace();
                }
                return;
            }
        }.start();

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(new Date());

        int j = this.height / 4 + 48;

        if (this.mc.isDemo()) {
            this.addDemoButtons(j, 24);
        } else {
            this.addSingleplayerMultiplayerButtons(j, 24);
        }

        this.buttonList.add(new GuiDiscraftButton(0, x, 167, buttonWidth, 20, I18n.format("menu.options")).addToolTip(I18n.format("button.tooltip.options")));

        this.buttonList.add(new GuiDiscraftButtonLanguage(5, x - 24, 47).addToolTip(I18n.format("button.tooltip.language")));

        this.buttonList.add(new GuiDiscraftButtonDiscord(7, x - 24, 71).addToolTip(I18n.format("button.tooltip.officialdiscord")));

        this.buttonList.add(new GuiDiscraftButtonExit(6, x - 24, 95).addToolTip(I18n.format("button.tooltip.quit")));

        synchronized (this.threadLock) {
            this.openGLWarning1Width = this.fontRenderer.getStringWidth(this.openGLWarning1);
            this.openGLWarning2Width = this.fontRenderer.getStringWidth(this.openGLWarning2);
            int k = Math.max(this.openGLWarning1Width, this.openGLWarning2Width);
            this.openGLWarningX1 = (this.width - k) / 2;
            this.openGLWarningY1 = (this.buttonList.get(0)).y - 24;
            this.openGLWarningX2 = this.openGLWarningX1 + k;
            this.openGLWarningY2 = this.openGLWarningY1 + 24;
        }

        this.mc.setConnectedToRealms(false);

        if (Minecraft.getMinecraft().gameSettings.getOptionOrdinalValue(GameSettings.Options.REALMS_NOTIFICATIONS) && !this.hasCheckedForRealmsNotification) {
            RealmsBridge realmsbridge = new RealmsBridge();
            this.realmsNotification = realmsbridge.getNotificationScreen(this);
            this.hasCheckedForRealmsNotification = true;
        }

        if (this.areRealmsNotificationsEnabled()) {
            this.realmsNotification.setGuiSize(this.width, this.height);
            this.realmsNotification.initGui();
        }
        modUpdateNotification = net.minecraftforge.client.gui.NotificationModUpdateScreen.init(new GuiMainMenu(), modButton);

        containerModules = new GuiDiscraftContainerModules(0, width + 1, 0, 50, height, this);
        addContainer(containerModules);

    }

    private void injectNews(List<String> news) {

        if (news != null) {
            menuNewsContainer.setTextList(news);
        } else {
            menuNewsContainer.setTextList(ImmutableList.of("Failed to grab news and updates!", "Are the Official Servers offline?"));
        }
    }

    /**
     * Adds Singleplayer and Multiplayer buttons on Main Menu for players who have bought the game.
     */
    private void addSingleplayerMultiplayerButtons(int p_73969_1_, int p_73969_2_) {

        int x = width / 2 - 173;

        int buttonWidth = 100;

        this.buttonList.add(new GuiDiscraftButton(1, x, 95, buttonWidth, 20, I18n.format("menu.singleplayer")).addToolTip(I18n.format("button.tooltip.singleplayer")));
        this.buttonList.add(new GuiDiscraftButton(2, x, 119, buttonWidth, 20, I18n.format("menu.multiplayer")).addToolTip(I18n.format("button.tooltip.multiplayer")));

        this.buttonList.add(modButton = new GuiDiscraftButton(6, x, 143, buttonWidth, 20, I18n.format("fml.menu.mods")).addToolTip(I18n.format("button.tooltip.mods", "" + ChatFormatting.GREEN + Loader.instance().getActiveModList().size() + ChatFormatting.RESET)));
    }

    /**
     * Adds Demo buttons on Main Menu for players who are playing Demo.
     */
    private void addDemoButtons(int p_73972_1_, int p_73972_2_) {

        int x = width / 2 - 173;

        this.buttonList.add(new GuiDiscraftButton(11, x, p_73972_1_, I18n.format("menu.playdemo")));
        this.buttonResetDemo = this.addButton(new GuiDiscraftButton(12, x, p_73972_1_ + p_73972_2_ * 1, I18n.format("menu.resetdemo")));
        ISaveFormat isaveformat = this.mc.getSaveLoader();
        WorldInfo worldinfo = isaveformat.getWorldInfo("Demo_World");

        if (worldinfo == null) {
            this.buttonResetDemo.enabled = false;
        }
    }

    /**
     * Called by the controls from the buttonList when activated. (Mouse pressed for buttons)
     */
    protected void actionPerformed(GuiButton button) {
        if (button.id == 0) {
            this.mc.displayGuiScreen(new GuiOptions(this, this.mc.gameSettings));
        }

        if (button.id == 1) {
            this.mc.displayGuiScreen(new GuiWorldSelection(this));
        }

        if (button.id == 2) {
            this.mc.displayGuiScreen(new GuiMultiplayer(this));
        }

        if (button.id == 4) {
            this.mc.shutdown();
        }

        if (button.id == 5) {
            this.mc.displayGuiScreen(new GuiLanguage(this, this.mc.gameSettings, this.mc.getLanguageManager()));
        }

        if (button.id == 6) {
            this.mc.displayGuiScreen(new net.minecraftforge.fml.client.GuiModList(this));
        }

        if (button.id == 7) {
            openURL(DiscraftReferences.officialDiscordURL);
            return;
        }

        if (button.id == 14 && this.realmsButton.visible) {
            this.switchToRealms();
        }

        if (button.id == 11) {
            this.mc.launchIntegratedServer("Demo_World", "Demo_World", WorldServerDemo.DEMO_WORLD_SETTINGS);
        }

        if (button.id == 12) {
            ISaveFormat isaveformat = this.mc.getSaveLoader();
            WorldInfo worldinfo = isaveformat.getWorldInfo("Demo_World");

            if (worldinfo != null) {
                this.mc.displayGuiScreen(new GuiYesNo(this, I18n.format("selectWorld.deleteQuestion"), "'" + worldinfo.getWorldName() + "' " + I18n.format("selectWorld.deleteWarning"), I18n.format("selectWorld.deleteButton"), I18n.format("gui.cancel"), 12));
            }
        }
    }

    private void switchToRealms() {
        RealmsBridge realmsbridge = new RealmsBridge();
        realmsbridge.switchToRealms(this);
    }

    public void confirmClicked(boolean result, int id) {
        if (result && id == 12) {
            ISaveFormat isaveformat = this.mc.getSaveLoader();
            isaveformat.flushCache();
            isaveformat.deleteWorldDirectory("Demo_World");
            this.mc.displayGuiScreen(this);
        } else if (id == 12) {
            this.mc.displayGuiScreen(this);
        } else if (id == 13) {
            if (result) {
                try {
                    Class<?> oclass = Class.forName("java.awt.Desktop");
                    Object object = oclass.getMethod("getDesktop").invoke(null);
                    oclass.getMethod("browse", URI.class).invoke(object, new URI(this.openGLWarningLink));
                } catch (Throwable throwable) {
                    LOGGER.error("Couldn't open link", throwable);
                }
            }

            this.mc.displayGuiScreen(this);
        }
    }

    /**
     * Draws the screen and all the components in it.
     */
    @Override
    public void drawScreen(int mouseX, int mouseY, float partialTicks) {

        int x = width / 2 - 173;

        if (mc.currentScreen instanceof GuiDiscraftManager
                || mc.currentScreen instanceof GuiDiscraftTextPrompt) {
            if (moduleFade < 0.8) {
                moduleFade += 0.1f;
            }
        } else {
            if (moduleFade > 0) {
                this.moduleFade -= 0.1f;
            }
        }

        GlStateManager.pushMatrix();
        float backgroundGradientSwing = (float) ((Math.sin(Discraft.getInstance().discraftVariables.smoothSwing / 80) + 1) * 100);
        GuiUtils.renderRectWithGradient(0, 0, width + (int) backgroundGradientSwing, height + (int) backgroundGradientSwing, 0xFF5F9F35, 0xFF2E4C1A, 0);
        GlStateManager.popMatrix();

        /* Player Information Container */
        GuiUtils.renderRectWithOutline(x, 47, 100, 44, 0x77000000, 0x77000000, 1);
        ScissorState.scissor(x, 47, 100, 44, true);
        float playerModelSwing = (float) ((Math.sin(Discraft.getInstance().discraftVariables.swing / 20) + 1) * 15 - 45);
        GuiUtils.renderPlayer(x, 34, (int) playerModelSwing);
        ScissorState.endScissor();

        /* Render Player Information */
        GuiUtils.renderText(Minecraft.getMinecraft().getSession().getUsername(), x + 3, 47 + 3, 0xFFFFFF);
        GuiUtils.renderText(I18n.format("menu.profile.coins", ChatFormatting.YELLOW + "25"), x + 3, 57 + 3, 0xFFFFFF);

        /* Render Player Count */
        GuiUtils.renderTextScaled(I18n.format("menu.profile.playercount", ChatFormatting.GREEN + "" + Discraft.getInstance().discraftVariables.playerCount + ChatFormatting.RESET), x + 2, 82 + 3, 0xFFFFFF, .5);

        GlStateManager.color(1.0F, 1.0F, 1.0F, 1.0F);

        GuiUtils.renderImageCentered(width / 2, 23, MENU_LOGO, 148, 40);

        if (this.openGLWarning1 != null && !this.openGLWarning1.isEmpty()) {
            drawRect(this.openGLWarningX1 - 2, this.openGLWarningY1 - 2, this.openGLWarningX2 + 2, this.openGLWarningY2 - 1, 1428160512);
            this.drawString(this.fontRenderer, this.openGLWarning1, this.openGLWarningX1, this.openGLWarningY1, -1);
            this.drawString(this.fontRenderer, this.openGLWarning2, (this.width - this.openGLWarning2Width) / 2, (this.buttonList.get(0)).y - 12, -1);
        }

        super.drawScreen(mouseX, mouseY, partialTicks);

        if (this.areRealmsNotificationsEnabled()) {
            this.realmsNotification.drawScreen(mouseX, mouseY, partialTicks);
        }

        this.modUpdateNotification.drawScreen(mouseX, mouseY, partialTicks);

        GuiUtils.renderRect(0, 0, width, height, 0xBB000000, this.moduleFade);

        drawIntro();

    }

    /**
     * Called when the mouse is clicked. Args : mouseX, mouseY, clickedButton
     */
    protected void mouseClicked(int mouseX, int mouseY, int mouseButton) {
        super.mouseClicked(mouseX, mouseY, mouseButton);

        synchronized (this.threadLock) {
            if (!this.openGLWarning1.isEmpty() && !StringUtils.isNullOrEmpty(this.openGLWarningLink) && mouseX >= this.openGLWarningX1 && mouseX <= this.openGLWarningX2 && mouseY >= this.openGLWarningY1 && mouseY <= this.openGLWarningY2) {
                GuiConfirmOpenLink guiconfirmopenlink = new GuiConfirmOpenLink(this, this.openGLWarningLink, 13, true);
                guiconfirmopenlink.disableSecurityWarning();
                this.mc.displayGuiScreen(guiconfirmopenlink);
            }
        }

    }

    /**
     * Called when the screen is unloaded. Used to disable keyboard repeat events
     */
    public void onGuiClosed() {
        if (this.realmsNotification != null) {
            this.realmsNotification.onGuiClosed();
        }
    }

    public void drawIntro(){

        if(!hasPlayedIntroSound){
            hasPlayedIntroSound = true;
            Minecraft.getMinecraft().getSoundHandler().playSound(PositionedSoundRecord.getMasterRecord(SoundEvents.UI_TOAST_CHALLENGE_COMPLETE, 1.0F));
        }

        if(introFadeFirst <= 0) {
            if (introFade > 0) {
                introFade -= 0.02f;
                hasSeenIntro = false;
            } else {
                hasSeenIntro = true;
            }
        } else {
            hasSeenIntro = false;
        }

        if(introFadeFirst > 0){
            introFadeFirst-=0.025f;
        }

        if(!hasSeenIntro){

            GuiUtils.renderRect(0,0,width,height,0xFF5E9D34,introFade);
            GuiUtils.renderImageCenteredTransparent(this.width / 2,this.height / 2,MENU_LOGO,296, 80,introFade);
            GuiUtils.renderRect(0,0,width,height,0xFF5E9D34,introFadeFirst);

        }

    }

    public static boolean hasSeenIntro(){
        return hasSeenIntro;
    }

}